### ISSUE TITLE
Migration to TypeScript ★

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-rest-api#127]
**Is your feature request related to a problem? Please describe.**
As JS has bad typing support so we plan to rely on superset of JS i.e - TS.
Similar issue that address this concern on client-side architecture. 
https://github.com/Ignitus/Ignitus-client/issues/477

**Describe the solution you'd like**
Before doing migration to TS, we should have to fix #126 

**Describe alternatives you've considered**
Prop-Types.

**Additional context**
Leave a comment if you have any Questions.

**Comment by divyanshu-rawat** [comment]
Support Added using #131 ☘️

**Comment by divyanshu-rawat** [comment]
#131 adds support for TS, migration will take place step by step.

**Comment by AnjaliGarg13** [comment]
@divyanshu-rawat I want to work on this issue.

**Comment by divyanshu-rawat** [comment]
Sure go ahead @AnjaliGarg13 👍

**Comment by divyanshu-rawat** [comment]
@Marvin9 if you have time & interest you can also try converting some controllers, routes to TS as well 😅, I have introduced TS but only to minor extent migration is still needed but compilation logic is already there.

**Comment by Marvin9** [comment]
Cool. Will start soon 👻

**Comment by divyanshu-rawat** [comment]
#151 takes care of it 🎯
