### ISSUE TITLE
LinkedIn Authentication ★

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-rest-api#138]
**Is your feature request related to a problem? Please describe.**
Ignitus already have a route for LinkedIn authentication.

**Describe the solution you'd like**
Implementing front end for LinkedIn authentication & testing Ignitus existing LinkedIn authentication for functionality.

**Describe alternatives you've considered**
N.A

**Additional context**
Ping me if you need any help & if you need more info.

**Comment by Paarmita** [comment]
In addition to this, we need authentication from Linkedin, Gmail, Github, and Facebook.

**Comment by ashutosh97** [comment]
@divyanshu-rawat I would like to work on this issue. I couldn't find a controller for the route you mentioned. Will you please guide me a bit on how to go about resolving this issue?

**Comment by majovanilla** [comment]
Hey @ashutosh97 are you working on this issue?? I would like to help.

**Comment by divyanshu-rawat** [comment]
@ashutosh97 doesn't seem to work on it currently, are you willing to work on it :) @majovanilla

**Comment by majovanilla** [comment]
Perfect!! I am going to check the repo and start working on it next week. I will let you know if I need more info. 😄

**Comment by Dishebh** [comment]
@divyanshu-rawat I see a route under `userRoutes`, but that is all commented out. Can you please give some more insights regarding the issue and what needs to be done here?
