### ISSUE TITLE
Reset password 🤦  🤦‍♀️

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-rest-api#139]
**Is your feature request related to a problem? Please describe.**
Ignitus already have support for resetting the password.

**Describe the solution you'd like**
Implement front-end & test exiting password reset functionality.

**Describe alternatives you've considered**
N.A

**Additional context**
Ping me if you need any help & if you need more info.

**Comment by ashutosh97** [comment]
Claiming

**Comment by ashutosh97** [comment]
@divyanshu-rawat Any specific UI requirements? Or just a reset password link below sign-in buttons would do fine?

**Comment by divyanshu-rawat** [comment]
@ashutosh97 let's discuss issues you have claimed and next steps in slack, if you are not in ignitus slack please join it https://bit.ly/JoinIgnitusSlack, and ping me once you join the slack.
