### ISSUE TITLE
API to render data of static landing page

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-rest-api#14]
**Is your feature request related to a problem? Please describe.**
Initially, data of Ignitus landing page is hardcoded, so in order to modify or add any information, changes need to be done in react components which is a bad practice.

**Describe the solution you'd like**
Create a RestAPI to render the data for a web app in the frontend.

**Additional context**
For eg., the [team,](https://github.com/Ignitus/Ignitus-Client-Side-Development/tree/teamselection/src/components/Team) [testimonials,](https://github.com/Ignitus/Ignitus-Client-Side-Development/tree/develop/src/components/Testimonial) [contributors](https://github.com/Ignitus/Ignitus-Client-Side-Development/tree/develop/src/components/Contributors) and [partners](https://github.com/Ignitus/Ignitus-Client-Side-Development/tree/develop/src/components/Partners) data need to be rendered from API

**Comment by niklabh** [comment]
https://github.com/Ignitus/Ignitus-rest-api/pull/15

**Comment by ATLowther** [comment]
This has been referenced by a merged pull request. Should this still be open? Or has it been resolved?

**Comment by Paarmita** [comment]
@ATLowther Only testimonial API is added, rest are remaining. So this issue is still open to working on.
