### ISSUE TITLE
Add jest and supertest packages for writing tests for API endpoints

### ISSUE THREAD

**Issue by Dishebh** [Ignitus/Ignitus-rest-api#155]
**Describe the solution you'd like**
Add jest and supertest packages for writing unit tests, integration tests and end-to-end tests for API endpoints, and various HTTP methods.

**Additional context**
Testing with jest and supertest: 
https://itnext.io/writing-tests-in-your-node-js-api-application-cfb5592df466
https://dev.to/nedsoft/testing-nodejs-express-api-with-jest-and-supertest-1km6

**Comment by Dishebh** [comment]
@divyanshu-rawat please let me know if I can go ahead with it :)

**Comment by divyanshu-rawat** [comment]
Sure @Dishebh go ahead 👍 keep in mind to add both testing frameworks as devDependencies. 🚀
