### ISSUE TITLE
CRUD operation for both Student and Professor with proper validation and authorization 

### ISSUE THREAD

**Issue by pranjalkumar** [Ignitus/Ignitus-rest-api#18]
**Describe the solution you'd like**
Student and Professor should be able to able to add, modify and delete all the information from their profile. Also, while making these features, keep the proper authorization for both the roles.

**Comment by ATLowther** [comment]
"all the information" seems pretty broad. What should be updatable, more specifically?

If somebody changes their email, which is attached to their login, are we prepared/wanting to handle this?

I assume user_role, verified, verifytoken, linkedin{} shouldn't be modifiable by the user, right? 

Are we just wanting to allow a password update or are there more fields that need to be added to the User Model?

**Comment by akshataw** [comment]
I would like to work on this. How should I start?
