### ISSUE TITLE
Add Contributions.md

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-rest-api#19]
**Describe the solution you'd like**
Detailed instruction about contributions to the repo and how to set up the API locally should be added for newcomers.
Can have a look to this for sample. [CONTRIBUTION.md](https://github.com/Ignitus/Ignitus-Client-Side-Development/blob/master/CONTRIBUTION.md)

**Comment by moulikcipherX** [comment]
I am working on this...

**Comment by Paarmita** [comment]
@moulikcipherX Provide a detailed installation guide 👍
