### ISSUE TITLE
Write Test Cases

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-rest-api#24]
Testing Node.js Applications.
Unit Testing Node.js Applications.

It would be great if we can make use of Mocha and Chai 👍 

- Mocha is a feature-rich JavaScript test framework running on Node.js and in the browser, making asynchronous testing simple and fun. Mocha tests run serially, allowing for flexible and accurate reporting, while mapping uncaught exceptions to the correct test cases.

- Chai is a BDD / TDD assertion library for node and the browser that can be delightfully paired with any javascript testing framework.

Write test cases for the api end points 👍 
Let me know if you have any Questions 👍

**Comment by kartikpandey2** [comment]
I am interested @divyanshu-rawat

**Comment by divyanshu-rawat** [comment]
@kartikpandey2  go ahead 👍

**Comment by debck** [comment]
Want to work on writing some unit tests.

**Comment by divyanshu-rawat** [comment]
@debck cool 👍

**Comment by pradnyasd** [comment]
I want to work on this testing issue. So what should I start with?

**Comment by divyanshu-rawat** [comment]
@pradnyasd you can start with any endpoint that you want to write test cases for ;)
