### ISSUE TITLE
Airbnb JavaScript Style Guide

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-rest-api#25]
Airbnb maintains a very popular JavaScript Style Guide that is used by many JavaScript developers worldwide. Following this style guide will ensure your code has a level of clarity that makes reading and maintaining your code easier for anyone who has to work on it.

ESLint is a tool for “linting” your code. It can analyze your code and warn you of potential errors. In order for it to work, you need to configure it with specific rules. Luckily, Airbnb — as part of their style guide — provides an ESLint configuration that anyone can use

Follow the thread to know more 👍 
- https://travishorn.com/setting-up-eslint-on-vs-code-with-airbnb-javascript-style-guide-6eb78a535ba6

**Comment by matcha440** [comment]
I can pick this one up, if you don't mind.  Thanks.

**Comment by divyanshu-rawat** [comment]
@matcha440 go ahead 👍
