### ISSUE TITLE
Add TypeScript Support

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-rest-api#26]
There are three popular ways to handle types in JS Applications: PropTypes, TypeScript and Flow.
As we are dealing with server-side Node.js application.
So, TypeScript will be a good choice 👍 

TypeScript is an open-source programming language developed and maintained by Microsoft. It is a strict syntactical superset of JavaScript, and adds optional static typing to the language.

**Comment by apravink** [comment]
I'd like to work on this but I would like a few more details. Is the intention here to add typescript and set up a tsconfig file or is it to defined custom types for the entire repo?

**Comment by apravink** [comment]
Cant push to the repo. Is this on your end or mine?
```ERROR: Permission to Ignitus/Ignitus-rest-api.git denied to apravink.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.```

**Comment by divyanshu-rawat** [comment]
@apravink Thanks for your interest.
Please fork the repo. and create a new branch then send the pull request, currently you don't have rights to directly push into the repo. master branch. :)
Let me know if you have any other Questions

**Comment by divyanshu-rawat** [comment]
@apravink you can setup up tsconfig file and define custom types as well, feel free to do whatever you thing is relavent in your opinion.

**Comment by Rupeshiya** [comment]
@apravink  are you still working on this ? 
@divyanshu-rawat  should I fix this ?

**Comment by Rupeshiya** [comment]
@divyanshu-rawat  should I send PR ?

**Comment by divyanshu-rawat** [comment]
@Rupeshiya sure 👍

**Comment by Rupeshiya** [comment]
@divyanshu-rawat  plz review :)
