### ISSUE TITLE
Add Istanbul

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-rest-api#27]
Code coverage - To get a better idea of how well our codebase is covered with tests, we can generate a coverage report.

This report will include metrics on:
- line coverage
- statement coverage
- branch coverage
- and function coverage

**Comment by parulgupta26** [comment]
created PR for this - https://github.com/Ignitus/Ignitus-rest-api/pull/35

**Comment by moulikcipherX** [comment]
Please close this issue..
