### ISSUE TITLE
Fix ESLINT Warnings

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-rest-api#31]
Fix ESLINT warnings 👍 
run ``` npm run lint ```

And see the errors log and then manually fix them as fixiable issue are already fixed by running.
 ``` npm run lint:fix ```

**Comment by mariadoesmath** [comment]
I can do this.

**Comment by Bharat23** [comment]
I can do this

**Comment by divyanshu-rawat** [comment]
@mariadoesmath go ahead 👍

**Comment by mariadoesmath** [comment]
BTW, your contribution docs say to clone a different repo which is kind of confusing. You want to fix eslint errors in  Ignitus-rest-api, not Ignitus-Client-Side-Development right?
