### ISSUE TITLE
API to render static data of team component

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-rest-api#37]
## Is your feature request related to a problem? Please describe.
Currently, data in Ignitus landing page is hardcoded in react component itself, but we want react component to send async request to the restful api endpoint and render data recieved from the response.

## Describe the solution you'd like
Create a RestAPI endpoint that will contain information (Designation,Name, Linkedin Profile URL, Github Profile URL) about each teammember.
Endpoint must perform CRUD operations.

![screenshot](https://user-images.githubusercontent.com/26546816/46671371-35352680-cbf2-11e8-9114-eb4ed4b4770b.png)

**Comment by trevorkirpaul** [comment]
I'm taking a shot at this :)

I mainly work with frontend/react code but I'm somewhat familiar with mongoose/mongoDB and node.

**Comment by divyanshu-rawat** [comment]
@trevorkirpaul Thanks that's Great 👍
