### ISSUE TITLE
Get User Information From JWT

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-rest-api#39]
Implement api endpoint to fetch user info from jwt token like '/userinfofromtoken'. or '/me'.
👍

**Comment by nirmalks** [comment]
I would like to work on this

**Comment by divyanshu-rawat** [comment]
@nirmalks great go ahead 👍

**Comment by nirmalks** [comment]
Hi @divyanshu-rawat ,

Correct me if I'm wrong, it looks like the JWT token is not stored in the DB. Am I missing something?         

```
if (result) {
      const token = jwt.sign({
            email: data[0].email,
            user_role: data[0].user_role,
            userId: data[0]._id,
          },
          secret,
          { expiresIn: '1h' });

          const clientData = {
            email: data[0].email,
            user_role: data[0].user_role,
          }

          return responseHandler.success(res, { token }, { clientData });
 }
```

**Comment by pranjalkumar** [comment]
Hey, @nirmalks 
It's REST API which is stateless which means that there is no need to store the tokens.

**Comment by divyanshu-rawat** [comment]
@nirmalks , actually it will be sent by the client in the request header once client is authenticated, so you need not to store it in db.

The purpose of this route is to fetch user information when user is authenticated and refreshes the window then it will called inside component did mount of react component and will send token in request object.

I hope you understand.

**Comment by divyanshu-rawat** [comment]
@nirmalks  we are actually looking for something like this.


```
exports.me = function(req,res){
    if (req.headers && req.headers.authorization || req.body.token) {
        var authorization = headers.authorization,
            decoded;
        try {
            decoded = jwt.verify(authorization, secret.secretToken);
        } catch (e) {
            return res.status(401).send('unauthorized');
        }
        var userId = decoded.id;
        // Fetch the user by id 
        User.findOne({_id: userId}).then(function(user){
            // Do something with the user
            return res.send(200);
        });
    }
    return res.send(500);
}
```

**Comment by nirmalks** [comment]
@divyanshu-rawat  Ok, Thanks. To confirm, the intention is to fetch the user information based on the JWT payload, right?
