### ISSUE TITLE
Add Redis for API Cache.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-rest-api#46]
**Is your feature request related to a problem? Please describe.**
Fetching data from an API can be costly, especially if your application is making multiple HTTP requests to an API endpoint. Problems like request throttling and network latency could become an issue really fast.

**Describe the solution you'd like**
Adding Redis to the existing node.js rest API.

**Additional context**
Redis, RE-dis is an open-source in-memory data structure project implementing a distributed, in-memory key-value database with optional durability.

**Comment by ikhnaton** [comment]
I can knock this out for you

**Comment by divyanshu-rawat** [comment]
@ikhnaton go ahead 👍

**Comment by ikhnaton** [comment]
Installation instructions don't work.  Vapid keys seem to be missing.  I've setup my local MongoDB and I can connect, but app seems to hang when I navigate to localhost:4000 (docs say 3000, but code shows 4000)  It's pretty straight forward to write the code you need, but I need a working environment to be able to test.

**Comment by divyanshu-rawat** [comment]
@ikhnaton you can change the port here - https://github.com/Ignitus/Ignitus-rest-api/blob/master/bin/www
Apart from that Vapid is for push notification you can comment out that code and try testing with postman.
Let me know if you have nay other Questions 👍
