### ISSUE TITLE
Get data from github API for Contributors

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-rest-api#51]
For the Contributors section in Team page, the contributor's data(profile pic, username, and profile URL) should be taken from the Github API Contributors of the 2 repositories of Ignitus [Client](https://github.com/Ignitus/Ignitus-Client-Side-Development) and [Backend](https://github.com/Ignitus/Ignitus-rest-api).
You need to integrate them both.

![screenshot from 2018-11-24 18-06-14](https://user-images.githubusercontent.com/26546816/48968311-ab131700-f013-11e8-9244-7a30569905bb.png)

**Comment by Rupeshiya** [comment]
@Paarmita  can you please tell me what type of data and what to do with data ?
I would like to work on this .

**Comment by Paarmita** [comment]
@Rupeshiya We need to render the profile pic, username, and profile URL from the API and create an endpoint for it to pass in the components.

**Comment by divyanshu-rawat** [comment]
@Rupeshiya instead of storing it in DB, you can directly call github api from the client-side, no need to involve server-side on this.

**Comment by moulikcipherX** [comment]
Any Update on this issue?

**Comment by divyanshu-rawat** [comment]
@moulikcipherX Issue is already fixed thanks for your Interest 👍
