### ISSUE TITLE
linkedin signup and login not working

### ISSUE THREAD

**Issue by kislaysr** [Ignitus/Ignitus-rest-api#56]
**Describe the bug**
On using /student/oauth/linkedin for signup the profileDataInsertion() function and req.cache.load() in linkedinlogin function are working is async so the user is saved after the query is made, making the "result" empty and the user is not logged in after signup. Also, there is typo controllers/user.js linkedinlogin function while creating const token =  jwt.sign(...) instead of result[0].user_role in data[0] is written making login not possible.

**To Reproduce**
1. hit the 'http://localhost:3000/student/oauth/linkedin' url
2. See error in cmd

**Expected behavior**
Jwt token should be created after linkedin signup and signin.

**Comment by divyanshu-rawat** [comment]
@Paarmita please have a look 👋.

**Comment by Paarmita** [comment]
@kislaysr would you like to work on it?

**Comment by kislaysr** [comment]
> @kislaysr would you like to work on it?

Yes, I will work on it.

**Comment by kislaysr** [comment]
@Paarmita @divyanshu-rawat the problem is not with profileDataInsertion() function somehow the query Users.find({email:user_email}) is not working inside user.save().then(...) thus the req.cahe.load(....) is not loading result. I am still not able to pinpoint the real issue.

**Comment by pranjalkumar** [comment]
Is this issue still persists. And please check that we have a valid linkedin handle registered with linked and that our callback page is registered on linkedin
